# Generated by Django 5.0.8 on 2024-10-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0005_remove_skillmodel_description_remove_skillmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivemodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
