# Generated by Django 5.0.8 on 2024-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0006_objetivemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationmodel',
            name='cer_address',
            field=models.TextField(null=True),
        ),
    ]
